# ----------------------------------------------------------------------
# 3D two-ball mesh — a ball `|x| ≤ R2` with two spherical holes of radius
# `R1` centred at `(±d/2, 0, 0)`. The 3D analog of `make_two_hole_mesh`
# (binary excision). Builder + topology only.
#
# Three regions (inside → outside), the 3D lift of the 2D construction:
#
#  1. Inner regions (one per hole): 6 `PatchInflation{3}` patches mapping the
#     hole sphere `R1` (the excision boundary) out to an axis-aligned cube of
#     half-side `L` centred at the hole. Off-centre (`center = (±d/2,0,0)`),
#     REVERSED radial range (`a_lo=1, a_hi=0`, sphere→cube), so the structured
#     radial index runs sphere→cube (the geometric inverse of `inflated_cube`).
#
#  2. Intermediate region: each hole's cube is connected to that hole's half of
#     the big cube ([∓A,0]×[−A,A]² resp. [0,A]×[−A,A]²) by a 6-frustum
#     "cube-in-cube" O-grid of straight-sided `PatchTrilinearHex` blocks. The
#     two O-grids share the seam plane `x=0`. :separated keeps all 12 frustums;
#     :touching (`L=d/2`, cubes meet at x=0) drops the 2 seam frustums → 10.
#
#  3. Outer region: 10 `PatchInflation` (big cube `A` → sphere `R_mid`) + 10
#     `PatchShell` (`R_mid` → `R2`). The `±x` faces are whole; the `±y/±z`
#     faces are split at `x=0` into the two holes' halves.
#
# Counts: separated = 12 + 12 + 20 = 44 patches; touching = 12 + 10 + 20 = 42.
# `R2 = Inf` gives a compactified (i⁰) outer boundary (the shells handle it).
#
# Interior connectivity is fixed by the topology (independent of geometry /
# resolution / precision / R2), so it is stored as frozen integer D₄ tables
# (no floating-point comparison in the shipped builder). The tables were
# generated once by the build-time auto-wire scaffold `_two_ball_autowire!`
# below (which matches the four physical corners of each quad face up to the
# eight D₄ transforms) and are pinned by the coordinate-consistency and det-J
# tests. The scaffold is retained but NOT called by the builder.

# Frozen interior connectivity tables (`_TWO_BALL_LINKS_{SEPARATED,TOUCHING}`),
# generated by the `_two_ball_autowire` scaffold below and consumed by the
# (FP-free) builder.
include("two_ball_tables.jl")

# The 4 corners of an axis-aligned box face, in a fixed ordering of the two
# free coordinates (so the inner and outer faces of a frustum correspond).
# box = (x0,x1,y0,y1,z0,z1); dir 1..6 = −x,+x,−y,+y,−z,+z.
@inline function _box_face(box::NTuple{6, T}, dir::Int) where {T}
    x0, x1, y0, y1, z0, z1 = box
    if dir == 1      # −x
        return ((x0, y0, z0), (x0, y1, z0), (x0, y1, z1), (x0, y0, z1))
    elseif dir == 2  # +x
        return ((x1, y0, z0), (x1, y1, z0), (x1, y1, z1), (x1, y0, z1))
    elseif dir == 3  # −y
        return ((x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1))
    elseif dir == 4  # +y
        return ((x0, y1, z0), (x1, y1, z0), (x1, y1, z1), (x0, y1, z1))
    elseif dir == 5  # −z
        return ((x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0))
    else             # +z
        return ((x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1))
    end
end

# ----- build-time auto-wire scaffold (used to generate the frozen tables;
# not called by the shipped builder) ---------------------------------------

# Physical positions of face `f`'s four corners (tangent (0,0),(Mt1,0),
# (Mt1,Mt2),(0,Mt2)) plus its tangent dims, as Float64 triples.
@inline function _ball_face_corners(pd::PatchDesc{3, T}, f::Int) where {T}
    d  = dims(pd)
    Mt = _face_tangent_dims(f, d)
    ts = ((0, 0), (Mt[1], 0), (Mt[1], Mt[2]), (0, Mt[2]))
    pos = ntuple(4) do k
        x = _patch_vertex_position(pd, _face_vert_to_idx(f, ts[k], d))
        (Float64(x[1]), Float64(x[2]), Float64(x[3]))
    end
    return pos, Mt
end

# D₄ orientation `o` mapping face `f` of `P` onto face `g` of `Q`: the unique
# `o ∈ 0..7` such that `P`'s corner at tangent `t` coincides physically with
# `Q`'s vertex at `_neigh_pq_vertex(o, t, Mt_P…)`. Returns −1 if none.
function _ball_match_orientation(patches, p, f, q, g, MtP, tol)
    dP = dims(patches[p]);  dQ = dims(patches[q])
    tsP = ((0, 0), (MtP[1], 0), (MtP[1], MtP[2]), (0, MtP[2]))
    for o in 0:7
        ok = true
        for k in 1:4
            t  = tsP[k]
            t2 = _neigh_pq_vertex(o, t[1], t[2], MtP[1], MtP[2])
            xP = _patch_vertex_position(patches[p], _face_vert_to_idx(f, t, dP))
            xQ = _patch_vertex_position(patches[q], _face_vert_to_idx(g, t2, dQ))
            if !(abs(Float64(xP[1] - xQ[1])) ≤ tol &&
                 abs(Float64(xP[2] - xQ[2])) ≤ tol &&
                 abs(Float64(xP[3] - xQ[3])) ≤ tol)
                ok = false; break
            end
        end
        ok && return o
    end
    return -1
end

# Wire every interior face by matching the four physical face-corners; emit
# the link list `(p, f, q, g, o)` (one per directed half-link). D₄ elements
# are not all self-inverse, so each half's orientation is matched separately.
function _two_ball_autowire(patches, boundary::Vector{Tuple{Int, Int}}, tol)
    n = length(patches)
    isb = falses(6, n)
    for (p, f) in boundary
        isb[f, p] = true
    end
    corners = Dict{Tuple{Int, Int}, NTuple{4, NTuple{3, Float64}}}()
    mts     = Dict{Tuple{Int, Int}, NTuple{2, Int}}()
    for p in 1:n, f in 1:6
        isb[f, p] && continue
        c, Mt = _ball_face_corners(patches[p], f)
        corners[(p, f)] = c;  mts[(p, f)] = Mt
    end
    sameset(a, b) =
        all(any(abs(ai[1]-bi[1])≤tol && abs(ai[2]-bi[2])≤tol && abs(ai[3]-bi[3])≤tol
                for bi in b) for ai in a)
    links = Tuple{Int, Int, Int, Int, Int}[]
    wired = falses(6, n)
    for p in 1:n, f in 1:6
        (isb[f, p] || wired[f, p]) && continue
        ca = corners[(p, f)]
        mq = 0; mg = 0; nmatch = 0
        for q in 1:n, g in 1:6
            (q == p && g == f) && continue
            (isb[g, q] || wired[g, q]) && continue
            sameset(ca, corners[(q, g)]) && sameset(corners[(q, g)], ca) || continue
            mq = q; mg = g; nmatch += 1
        end
        nmatch == 1 ||
            error("_two_ball_autowire: face (patch=$p, face=$f) has $(nmatch) " *
                  "matching neighbours (expected 1).")
        o_pq = _ball_match_orientation(patches, p, f, mq, mg, mts[(p, f)], tol)
        o_qp = _ball_match_orientation(patches, mq, mg, p, f, mts[(mq, mg)], tol)
        (o_pq ≥ 0 && o_qp ≥ 0) ||
            error("_two_ball_autowire: no D₄ orientation for ($p,$f)↔($mq,$mg).")
        push!(links, (p, f, mq, mg, o_pq))
        push!(links, (mq, mg, p, f, o_qp))
        wired[f, p] = true;  wired[mg, mq] = true
    end
    return links
end

"""
    make_two_ball_mesh(::Type{T}, R1, R2, d, M; kwargs...) → Mesh{3, T}

Build a conforming hex mesh of the ball `|x| ≤ R2` with two spherical holes of
radius `R1` centred at `(±d/2, 0, 0)` — the 3D binary-excision domain and the
3D analog of [`make_two_hole_mesh`](@ref).

Each hole sphere is wrapped by 6 `Inflation` patches (sphere → cube of half-side
`L`); a 6-frustum `TrilinearHex` "cube-in-cube" O-grid connects each hole cube
to that hole's half of the big cube (half-side `A`); and an outer ring of 10
`Inflation` + 10 `Shell` patches maps the big cube out through sphere `R_mid` to
the outer sphere `R2`.

Geometry knobs (default from `R1,R2,d`): `L` (hole-cube half-side, default
`1.5·R1`, requires `R1 < L`); `A` (big-cube half-side, default `2(d/2+L)`);
`R_mid` (inflation/shell interface, default `1.5·√3·A`, requires `√3·A < R_mid`).
`M` is the cells per cube-face edge; radial counts `M_h,M_b,M_i,M_s` default
from the cube-edge spacing.

`mode = :separated` (default) keeps the two seam frustums; `mode = :touching`
forces `L = d/2` so the hole cubes meet at `x = 0`, drops the seam frustums
(42 patches), and requires `R1 < d/2`. `R2 = Inf` gives a compactified outer
boundary (i⁰). Hole spheres are tagged `inner_bc` (default `:excision`); the
outer sphere `outer_bc` (default `:dirichlet`).
"""
function make_two_ball_mesh(::Type{T}, R1::Real, R2::Real, d::Real, M::Int;
                            L::Union{Nothing, Real} = nothing,
                            A::Union{Nothing, Real} = nothing,
                            R_mid::Union{Nothing, Real} = nothing,
                            M_h::Union{Nothing, Int} = nothing,
                            M_b::Union{Nothing, Int} = nothing,
                            M_i::Union{Nothing, Int} = nothing,
                            M_s::Union{Nothing, Int} = nothing,
                            outer_bc::Symbol = :dirichlet,
                            inner_bc::Symbol = :excision,
                            mode::Symbol = :separated) where {T}
    skel = _two_ball_skeleton(T, R1, R2, d, M; L, A, R_mid,
                              M_h, M_b, M_i, M_s, outer_bc, inner_bc, mode)
    return _skeleton_to_mesh(skel)
end

# Geometry + patch construction, shared by `_two_ball_skeleton` (which wires
# the interior from the frozen tables) and the `_two_ball_autowire` generator.
# Returns `(patches, boundary, touching)` where `boundary` lists the `(patch,
# face)` pairs carrying a boundary tag.
function _two_ball_patches(::Type{T}, R1::Real, R2::Real, d::Real, M::Int;
                            L::Union{Nothing, Real} = nothing,
                            A::Union{Nothing, Real} = nothing,
                            R_mid::Union{Nothing, Real} = nothing,
                            M_h::Union{Nothing, Int} = nothing,
                            M_b::Union{Nothing, Int} = nothing,
                            M_i::Union{Nothing, Int} = nothing,
                            M_s::Union{Nothing, Int} = nothing,
                            outer_bc::Symbol = :dirichlet,
                            inner_bc::Symbol = :excision,
                            mode::Symbol = :separated) where {T}
    outer_tag = _shell_bc_tag(outer_bc; outer = true)
    inner_tag = _shell_bc_tag(inner_bc; outer = false)
    mode === :separated || mode === :touching ||
        error("make_two_ball_mesh: mode must be :separated or :touching, got $(repr(mode))")
    touching = mode === :touching
    @assert M ≥ 1
    @assert R1 > 0
    @assert R2 > 0

    R1f = Float64(R1);  R2f = Float64(R2)
    sf  = Float64(d) / 2
    if touching
        L === nothing ||
            error("make_two_ball_mesh: `L` is fixed to d/2 in :touching mode; do not pass it.")
        Lf = sf
    else
        Lf = L === nothing ? 1.5 * R1f : Float64(L)
    end
    Af  = A     === nothing ? 2.0 * (sf + Lf)        : Float64(A)
    Rmf = R_mid === nothing ? 1.5 * sqrt(3.0) * Af   : Float64(R_mid)
    @assert R1f < Lf  "hole-cube half-side L must exceed R1; in :touching mode this means R1 < d/2"
    touching || @assert Lf < sf  "holes overlap: need L < d/2 (use mode=:touching for close holes)"
    @assert Af > sf + Lf  "big cube must contain the hole cubes (A > d/2 + L)"
    @assert sqrt(3.0) * Af < Rmf  "R_mid must enclose the big-cube corner (√3·A)"
    @assert isinf(R2f) || Rmf < R2f  "R_mid must be inside the outer sphere R2"

    hf = 2 * Lf / M
    Mh = M_h === nothing ? max(1, round(Int, (Lf - R1f) / hf)) : M_h
    Mb = M_b === nothing ? max(1, round(Int, (Af - (sf + Lf)) / hf)) : M_b
    Mi = M_i === nothing ? max(1, round(Int, (Rmf - (1 + sqrt(3.0)) / 2 * Af) / hf)) : M_i
    Ms = M_s !== nothing ? M_s :
         isinf(R2f) ? M :                              # compactified: no finite extent
         max(1, round(Int, (R2f - Rmf) / hf))
    @assert Mh ≥ 1 && Mb ≥ 1 && Mi ≥ 1 && Ms ≥ 1

    sv = T(sf);  Lv = T(Lf);  Av = T(Af);  Rmv = T(Rmf)
    R1v = T(R1f);  R2v = T(R2f)
    z = zero(T);  o = one(T)

    patches = PatchDesc{3, T}[]

    # --- 1. Hole inflations (patches 1–12). Reversed radial range
    #        (a_lo=1 sphere, a_hi=0 cube), off-centre. 6 dirs per hole. ----
    for cx in (-sv, sv)
        for dir in 1:6
            push!(patches,
                  PatchDesc(PatchInflation{3, T}((Mh, M, M), Int8(dir),
                                                 o, z, -o, o, -o, o,
                                                 Lv, R1v, (cx, z, z))))
        end
    end

    # --- 2. Intermediate frustums (TrilinearHex). For each hole, 6 frustums
    #        mapping each hole-cube face to that hole's outer-box face.
    #        `frustum` builds an 8-corner hex (inner face = ζ=0, outer = ζ=1),
    #        flipping the ξ/η winding when needed so `det J > 0`. ----------
    function frustum(in4::NTuple{4, NTuple{3, T}}, out4::NTuple{4, NTuple{3, T}})
        c = (in4[1], in4[2], in4[3], in4[4], out4[1], out4[2], out4[3], out4[4])
        verts = ntuple(v -> SVector{3, T}(c[v]), Val(8))
        J = trilinear_jacobian(verts, one(T) / 2, one(T) / 2, one(T) / 2)
        if det(J) < z   # flip ξ/η winding (swap corners 2↔4 on both faces)
            c = (in4[1], in4[4], in4[3], in4[2], out4[1], out4[4], out4[3], out4[2])
        end
        return PatchDesc(PatchTrilinearHex{3, T}((M, M, Mb), c))
    end
    hole_cubes = ((-sv - Lv, -sv + Lv, -Lv, Lv, -Lv, Lv),
                  ( sv - Lv,  sv + Lv, -Lv, Lv, -Lv, Lv))
    outer_boxes = ((-Av, z, -Av, Av, -Av, Av),     # hole 1: x ∈ [−A, 0]
                   (z,  Av, -Av, Av, -Av, Av))     # hole 2: x ∈ [0, A]
    seam_dir = (2, 1)   # hole1's +x face / hole2's −x face → the seam plane
    for hole in 1:2
        for dir in 1:6
            (touching && dir == seam_dir[hole]) && continue
            push!(patches, frustum(_box_face(hole_cubes[hole], dir),
                                    _box_face(outer_boxes[hole], dir)))
        end
    end

    # --- 3. Outer ring: 10 inflation (cube A → sphere R_mid) + 10 shell
    #        (R_mid → R2). ±x whole; ±y,±z split at x=0. Each spec is
    #        (dir, b_lo, b_hi, c_lo, c_hi); the split coordinate (b or c =
    #        the one carrying x) ranges over [−1,0] (hole 1) / [0,1] (hole 2).
    outer_specs = ((2, -o,  o, -o,  o),   # −x  whole
                   (1, -o,  o, -o,  o),   # +x  whole
                   (3, -o,  o, -o,  z),   # +y  x = A·c < 0  (hole 1)
                   (3, -o,  o,  z,  o),   # +y  x > 0        (hole 2)
                   (4, -o,  z, -o,  o),   # −y  x = A·b < 0
                   (4,  z,  o, -o,  o),   # −y  x > 0
                   (5, -o,  z, -o,  o),   # +z  x = A·b < 0
                   (5,  z,  o, -o,  o),   # +z  x > 0
                   (6, -o,  o, -o,  z),   # −z  x = A·c < 0
                   (6, -o,  o,  z,  o))   # −z  x > 0
    for (dir, blo, bhi, clo, chi) in outer_specs
        push!(patches, PatchDesc(PatchInflation{3, T}((Mi, M, M), Int8(dir),
                                                      z, o, blo, bhi, clo, chi,
                                                      Av, Rmv)))
    end
    for (dir, blo, bhi, clo, chi) in outer_specs
        push!(patches, PatchDesc(PatchShell{3, T}((Ms, M, M), Int8(dir),
                                                  z, o, blo, bhi, clo, chi,
                                                  Rmv, R2v)))
    end
    @assert length(patches) == (touching ? 42 : 44)

    # Boundary faces: hole spheres (face 1 = a_lo = sphere of patches 1–12),
    # outer sphere (face 2 of the 10 shells = last 10 patches).
    boundary = Tuple{Int, Int}[(p, 1) for p in 1:12]
    np = length(patches)
    append!(boundary, [(p, 2) for p in (np - 9):np])
    return patches, boundary, touching, (inner_tag, outer_tag)
end

function _two_ball_skeleton(::Type{T}, R1::Real, R2::Real, d::Real, M::Int;
                            mode::Symbol = :separated, kwargs...) where {T}
    patches, boundary, touching, (inner_tag, outer_tag) =
        _two_ball_patches(T, R1, R2, d, M; mode, kwargs...)
    faces = Matrix{FaceLink}(undef, 6, length(patches))
    for (p, f) in boundary
        faces[f, p] = boundary_link(f == 1 ? inner_tag : outer_tag)
    end
    links = touching ? _TWO_BALL_LINKS_TOUCHING : _TWO_BALL_LINKS_SEPARATED
    for (p, f, q, g, oo) in links
        faces[f, p] = interior_link(q, g, Int8(oo))
    end
    return SkeletonMesh{3, T}(patches, faces)
end
